<?php
namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Entity\Sample;


/**
 * SampleRepository
 *
 * This class was generated by the Doctrine ORM.
 */
class SampleRepository extends EntityRepository
{
}
