<?php
namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Entity\Settings;


/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM.
 */
class SettingsRepository extends EntityRepository
{
    public function getPreferences($offset, $limit)
    {
        return parent::findBy(array(),array('settingKey' => 'asc'), $limit, $offset);
    }

    public function getPreferencesByKey($key)
    {
        return parent::findOneBy(array('settingKey' => $key));
    }

    public function hasSettingKey($key)
    {
        return null;
    }
}
